language: python
python:
  - '3.8'
  - '3.7'
  - '3.6'
os:
  - linux
dist: bionic
cache: pip

before_install:
  - sudo apt-get install -y gfortran
  - pip uninstall -y numpy

install: pip install -r requirements.txt coverage coveralls

script: coverage run --include=tom_* manage.py test --exclude-tag=canary

after_success: coveralls

stages:
  - "Style Checks"
  - "test"

jobs:
  include:
    - stage: "Style Checks"
      if: type != cron
      install: pip install -I flake8
      script: flake8 tom_* --exclude=*/migrations/* --max-line-length=120

    - stage: "test"
      if: type != cron
      os: osx
      language: shell
      before_install: pip3 install -U pip
